#!/bin/bash

if [[ "$#" -lt 1 ]]; then
    echo "usage: `basename $0` <repo>"
    exit 1
fi

repo="$1"

curl -u 'kylcarte' https://api.github.com/user/repos -d "{\"name\":\"$repo\"}"
# Remember replace USER with your username and REPO with your repository/application name!
# git remote add origin git@github.com:kylcarte/$repo.git
# git push origin master

