#!/bin/bash

prg=`basename $0`
function usage {
    echo "usage: $prg <repo>"
    exit 1
}

case $# in
1)  ;;
*)  usage
    ;;
esac

repo="$1"
user=`git config --get github.user`

if confirm -y "Create github repository '$repo'?"
then
    if ! curl -u "$user" https://api.github.com/user/repos -d "{\"name\":\"$repo\"}"
    then
        echo "Repository creation failed:"
        echo "$res"
    fi
fi

