#!/bin/bash

prg=`basename $0`
function usage {
    echo "usage: $prg <repo>"
    exit 1
}

case $# in
1)  ;;
*)  usage
    ;;
esac

repo="$1"
user=`git config --get github.user`

git-create "$repo"
git init
git remote add origin git@github.com:${user}/${repo}.git
git push --set-upstream origin master

