#!/bin/bash

if [[ "$#" -lt 1 ]]; then
    exit 1
fi

path=`path-exists "$1"`

if [[ "$?" -ne 0 ]]; then
    echo "Path '$path' does not exist"
    if confirm -y "Create?"
    then
        mkdir -p "$path"
    fi
fi

